package silvia

import (
	"database/sql"
	"fmt"
	"reflect"
	"testing"
	"time"
)

var testStrings = []string{}

var transformResults = []struct {
	title    string
	request  string
	expected map[string]interface{}
}{
	{
		`Test 0`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742415&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=93&eg=event&et=hxgj6t&en=Step4Optionals&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:46:55+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(93), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hxgj6t", true},
			"En":         sql.NullString{"Step4Optionals", true},
		},
	},
	{
		`Test 1`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742462&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&ls=-1&eg=install&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{int64(-1), true},
			"Cs":         sql.NullInt64{Valid: false},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"install", true},
			"Et":         sql.NullString{Valid: false},
			"En":         sql.NullString{Valid: false},
		},
	},
	{
		`Test 2`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742467&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=144&eg=event&et=9x7o0n&en=Step3Regularity&ci=Saint+Petersburg`,
		map[string]interface{}{

			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:47+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(144), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"9x7o0n", true},
			"En":         sql.NullString{"Step3Regularity", true},
		},
	},
	{
		`Test 3`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742469&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=146&eg=event&et=hiagd3&en=Step2DateTime&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:49+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(146), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hiagd3", true},
			"En":         sql.NullString{"Step2DateTime", true},
		},
	},
	{
		`Test 4`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=kvszq2&tr_network=mgcom&tr_campaign=cpa&tr_adgroup=unilead&imp=0&org=0&adid=bbfc98b488e6c7149d16aa5f99c350f9&idfa=9A9AF28D-EDCF-4CBD-BD4E-B4F7017C5B56&mt=fingerprint&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=78.107.237.234&clt=1448455383&it=1448474126&ct=1460742470&reg=zz&c=ru&lng=ru&dn=iPhone8%2C1&dt=phone&os=ios&osv=9.3.1&env=production&tre=0&tz=UTC%2B0300&ls=93&eg=session&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"kvszq2", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"mgcom", true},
			"TrCampaign": sql.NullString{"cpa", true},
			"TrAdgroup":  sql.NullString{"unilead", true},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(0), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"bbfc98b488e6c7149d16aa5f99c350f9", true},
			"Idfa":       sql.NullString{"9A9AF28D-EDCF-4CBD-BD4E-B4F7017C5B56", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{"fingerprint", true},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"78.107.237.234", true},
			"Clt":        NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2015-11-25T15:43:03+03:00"); return t }(), true},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2015-11-25T20:55:26+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:50+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone8,1", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{int64(93), true},
			"Cs":         sql.NullInt64{Valid: false},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"session", true},
			"Et":         sql.NullString{Valid: false},
			"En":         sql.NullString{Valid: false},
		},
	},
	{
		`Test 5`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742471&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=148&eg=event&et=cbw1dm&en=Step1Rooms&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:51+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(148), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"cbw1dm", true},
			"En":         sql.NullString{"Step1Rooms", true},
		},
	},
	{
		`Test 6`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742475&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=153&eg=event&et=hiagd3&en=Step2DateTime&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:55+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(153), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hiagd3", true},
			"En":         sql.NullString{"Step2DateTime", true},
		},
	},
	{
		`Test 7`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742478&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=16&eg=event&et=jring0&en=SMS+SignIn&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:58+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(16), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"jring0", true},
			"En":         sql.NullString{"SMS SignIn", true},
		},
	},
	{
		`Test 8`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742479&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=157&eg=event&et=9x7o0n&en=Step3Regularity&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:59+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(157), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"9x7o0n", true},
			"En":         sql.NullString{"Step3Regularity", true},
		},
	},
	{
		`Test 9`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742485&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=23&eg=event&et=cbw1dm&en=Step1Rooms&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:05+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(23), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"cbw1dm", true},
			"En":         sql.NullString{"Step1Rooms", true},
		},
	},
	{
		`Test 10`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742537&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=75&eg=event&et=9x7o0n&en=Step3Regularity&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:57+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(75), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"9x7o0n", true},
			"En":         sql.NullString{"Step3Regularity", true},
		},
	},
	{
		`Test 11`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742525&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=63&eg=event&et=hiagd3&en=Step2DateTime&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:45+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(63), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hiagd3", true},
			"En":         sql.NullString{"Step2DateTime", true},
		},
	},
	{
		`Test 12`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742514&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=191&eg=event&et=cbw1dm&en=Step1Rooms&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:34+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(191), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"cbw1dm", true},
			"En":         sql.NullString{"Step1Rooms", true},
		},
	},
	{
		`Test 13`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=f72cc00eddcb12cba2b82836f4a57e27&idfa=13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55&ua=Qlean%2F59+CFNetwork%2F758.3.15+Darwin%2F15.4.0&ip=37.153.16.3&it=1452553329&ct=1460742513&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.1&env=production&tre=1&tz=UTC%2B0300&cs=191&eg=event&et=hiagd3&en=Step2DateTime&ci=Saint+Petersburg`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"f72cc00eddcb12cba2b82836f4a57e27", true},
			"Idfa":       sql.NullString{"13B32DF4-F9F0-4556-BFBE-F5B2B7B69B55", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.3.15 Darwin/15.4.0", true},
			"Ip":         sql.NullString{"37.153.16.3", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-01-12T02:02:09+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:33+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.1", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(1), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(191), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hiagd3", true},
			"En":         sql.NullString{"Step2DateTime", true},
		},
	},
	{
		`Test 14`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742507&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=45&eg=event&et=cbw1dm&en=Step1Rooms&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:27+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(45), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"cbw1dm", true},
			"En":         sql.NullString{"Step1Rooms", true},
		},
	},
	{
		`Test 15`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742498&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=36&eg=event&et=cbw1dm&en=Step1Rooms&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:18+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(36), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"cbw1dm", true},
			"En":         sql.NullString{"Step1Rooms", true},
		},
	},
	{
		`Test 16`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742497&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=35&eg=event&et=hiagd3&en=Step2DateTime&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:17+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(35), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"hiagd3", true},
			"En":         sql.NullString{"Step2DateTime", true},
		},
	},
	{
		`Test 17`,
		`/stats/adjust?aid=1011771034&an=com.qlean.qlean&av=1.4.8&st=itunes&tr=omxc35&tr_network=Organic&imp=0&org=1&adid=c5a5a51a5d716285af3d7a248d52ee31&idfa=1E5321A6-2A58-448A-952A-ABE57E93D991&ua=Qlean%2F59+CFNetwork%2F758.4.1+Darwin%2F15.5.0&ip=109.173.35.252&it=1460742462&ct=1460742495&reg=zz&c=ru&lng=ru&dn=iPhone7%2C2&dt=phone&os=ios&osv=9.3.2&env=production&tre=0&tz=UTC%2B0300&cs=33&eg=event&et=9x7o0n&en=Step3Regularity&ci=Moscow`,
		map[string]interface{}{
			"Aid":        sql.NullString{"1011771034", true},
			"An":         sql.NullString{"com.qlean.qlean", true},
			"Av":         sql.NullString{"1.4.8", true},
			"St":         sql.NullString{"itunes", true},
			"Tr":         sql.NullString{"omxc35", true},
			"Ptr":        sql.NullString{Valid: false},
			"TrNetwork":  sql.NullString{"Organic", true},
			"TrCampaign": sql.NullString{Valid: false},
			"TrAdgroup":  sql.NullString{Valid: false},
			"TrCreative": sql.NullString{Valid: false},
			"Imp":        sql.NullInt64{int64(0), true},
			"Org":        sql.NullInt64{int64(1), true},
			"Rej":        sql.NullString{Valid: false},
			"Adid":       sql.NullString{"c5a5a51a5d716285af3d7a248d52ee31", true},
			"Idfa":       sql.NullString{"1E5321A6-2A58-448A-952A-ABE57E93D991", true},
			"Anid":       sql.NullString{Valid: false},
			"Mac":        sql.NullString{Valid: false},
			"Mt":         sql.NullString{Valid: false},
			"Ref":        sql.NullString{Valid: false},
			"Ua":         sql.NullString{"Qlean/59 CFNetwork/758.4.1 Darwin/15.5.0", true},
			"Ip":         sql.NullString{"109.173.35.252", true},
			"Clt":        NullTime{Valid: false},
			"It":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:47:42+03:00"); return t }(), true},
			"Ct":         NullTime{func() time.Time { t, _ := time.Parse(time.RFC3339, "2016-04-15T20:48:15+03:00"); return t }(), true},
			"Rt":         NullTime{Valid: false},
			"Reg":        sql.NullString{"zz", true},
			"C":          sql.NullString{"ru", true},
			"Lng":        sql.NullString{"ru", true},
			"Dn":         sql.NullString{"iPhone7,2", true},
			"Dt":         sql.NullString{"phone", true},
			"Os":         sql.NullString{"ios", true},
			"Osv":        sql.NullString{"9.3.2", true},
			"Env":        sql.NullString{"production", true},
			"Tre":        sql.NullInt64{int64(0), true},
			"Tz":         sql.NullString{"UTC+0300", true},
			"Ls":         sql.NullInt64{Valid: false},
			"Cs":         sql.NullInt64{int64(33), true},
			"Dl":         sql.NullString{Valid: false},
			"Pp":         sql.NullString{Valid: false},
			"FbCgn":      sql.NullString{Valid: false},
			"FbCgid":     sql.NullString{Valid: false},
			"FbCn":       sql.NullString{Valid: false},
			"GbCid":      sql.NullString{Valid: false},
			"FbAdn":      sql.NullString{Valid: false},
			"FbAdid":     sql.NullString{Valid: false},
			"Pubp":       sql.NullString{Valid: false},
			"L":          sql.NullString{Valid: false},
			"Eg":         sql.NullString{"event", true},
			"Et":         sql.NullString{"9x7o0n", true},
			"En":         sql.NullString{"Step3Regularity", true},
		},
	},
}

func TestAdjustTransform(t *testing.T) {
	for _, testCase := range transformResults {
		event := &AdjustEvent{}
		event.Transform([]byte(testCase.request))
		eventValues := reflect.ValueOf(event).Elem()
		eventTypes := reflect.TypeOf(*event)
		for fieldName, expectedValue := range testCase.expected {
			fieldType, exist := eventTypes.FieldByName(fieldName)
			if !exist {
				t.Errorf("Falied on: %s\nField name: %s not exist", testCase.title, fieldName)
				continue
			}
			fieldValue := eventValues.FieldByName(fieldType.Name).Interface()
			if fieldValue != expectedValue {
				t.Errorf("Falied on: %s[%s]\nFieldValue[%T]: %+v\nExpectedValue[%T]: %+v\n\n", testCase.title, fieldName, fieldValue, fieldValue, expectedValue, expectedValue)
			}
		}
	}
}

func PrintAdjust(t *testing.T) {
	for i, adjustString := range testStrings {
		event := &AdjustEvent{}
		event.Transform([]byte(adjustString))
		fmt.Printf("\n`Test %d`,\n", i)
		fmt.Printf("\n`%s`,\n", adjustString)
		event.PrintStatement()
		fmt.Println()
	}
}

func (event *AdjustEvent) PrintStatement() {
	nullStringType := reflect.TypeOf(sql.NullString{})
	nullInt64Type := reflect.TypeOf(sql.NullInt64{})
	NullTimeType := reflect.TypeOf(NullTime{})
	structType := reflect.TypeOf(*event)
	eventValues := reflect.ValueOf(event).Elem()

	for i := 0; i < structType.NumField(); i++ {
		field := structType.Field(i)
		fieldValue := eventValues.FieldByName(field.Name)
		switch field.Type {
		case nullStringType:
			fmt.Printf(`"%s": `, field.Name)
			if fieldValue.FieldByName("Valid").Bool() {
				fmt.Printf(`sql.NullString{"%s", true}`, fieldValue.FieldByName("String").String())
			} else {
				fmt.Printf(`sql.NullString{Valid: false}`)
			}
			fmt.Printf(",\n")
		case nullInt64Type:
			fmt.Printf(`"%s": `, field.Name)
			if fieldValue.FieldByName("Valid").Bool() {
				fmt.Printf(`sql.NullInt64{int64(%d), true}`, fieldValue.FieldByName("Int64").Int())
			} else {
				fmt.Printf(`sql.NullInt64{Valid: false}`)
			}
			fmt.Printf(",\n")
		case NullTimeType:
			fmt.Printf(`"%s": `, field.Name)
			if fieldValue.FieldByName("Valid").Bool() {
				fmt.Printf(`NullTime{ func () time.Time { t, _ := time.Parse(time.RFC3339, "%s"); return t;}() , true}`, fieldValue.FieldByName("Time").Interface().(time.Time).Format(time.RFC3339))
			} else {
				fmt.Printf(`NullTime{Valid: false}`)
			}
			fmt.Printf(",\n")
		}
	}
}
