create schema if not exists adjust;

create table if not exists adjust.events
(
	loaded_at timestamp default sysdate not null,
	event_group varchar(32) encode bytedict,
	event_token varchar(32) encode bytedict,
	event_name varchar(128),
	idfa varchar(128),
	app_id varchar(255),
	app_name varchar(32),
	app_version varchar(16),
	store varchar(16),
	tracker varchar(16),
	previous_tracker varchar(16),
	tracker_network varchar(255),
	tracker_campaign varchar(255),
	tracker_adgroup varchar(255),
	tracker_creative varchar(255),
	label varchar(255),
	clicked_at timestamp,
	installed_at timestamp,
	event_at timestamp,
	reattributed_at timestamp,
	impression_based smallint,
	is_organic smallint,
	rejection_reason varchar(255),
	adjust_device_id varchar(128),
	android_id varchar(128),
	mac_sha1 varchar(128),
	match_type varchar(128),
	referrer varchar(65535),
	user_agent varchar(65535),
	ip_address varchar(45),
	region varchar(8),
	country varchar(8),
	language varchar(8),
	device_name varchar(128),
	device_type varchar(128),
	os_name varchar(128),
	os_version varchar(128),
	environment varchar(16),
	tracking_enabled smallint,
	device_timezone varchar(16),
	last_session_sec integer encode bytedict,
	current_session_sec integer,
	deeplink varchar(65535),
	partner_parameters varchar(65535),
	publisher_parameters varchar(65535),
	fb_campaign_group_name varchar(255),
	fb_campaign_group_id varchar(64),
	fb_campaign_name varchar(255),
	fb_campaign_id varchar(64),
	fb_adgroup_name varchar(255),
	fb_adgroup_id varchar(64),
	city varchar(32)
)
;
